language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

before_script:
  - composer self-update
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - OCULAR_ENV='5.4'

script:
  - vendor/bin/phpunit
  - vendor/bin/php-cs-fixer --diff --dry-run -vv fix
  - if [ $(phpenv version-name) = $OCULAR_ENV ]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
